name: Build Rust CLI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README**"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: serial-linux
            asset_name: serial
          - os: windows-latest
            artifact_name: serial-windows
            asset_name: serial.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Build project
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/${{ matrix.asset_name }}
